# Ustawienia PM 2.5
pm25_data_link: "https://powietrze.gios.gov.pl/pjp/archives/downloadFile/" #link do strony archiwum

metadata_id: "622"
pm25_daily_limit: "15.0" #Wartość dobowej normy PM2.5, powyżej której dzień uznawany jest za przekroczenie normy

# Lata są definiowane jako klucze słownika.
# Jest to spowodowane koniecznością przekazywania linku do archiwum z danymi pm2.5oraz nazwy surowego pliku
# w pobranym archiwum osobnie dla każdego roku
years:
  2015:
    archive_id: "236"
    filename: "2015_PM25_1g.xlsx"
  2018:
    archive_id: "603"
    filename: "2018_PM25_1g.xlsx"
  2021:
    archive_id: "486"
    filename: "2021_PM25_1g.xlsx"
  2024:
    archive_id: "582"
    filename: "2024_PM25_1g.xlsx"

cities:
  - "Katowice"
  - "Warszawa"
  - "Kraków"

# Ustawienia przeglądu publikacji
user_entrez_email: "m.khrabust@student.uw.edu.pl"
user_entrez_api_key: "cf88f96a609dbbbaa42b355f2793394f2f08" # Może pozostać puste

pubmed_queries:
  - "PM2.5 AND Poland"
  - "air pollution AND lung"
  - "particulate matter AND health"

retmax: 1000

sample_size: 100